[[Glibc]]
arch = "i686"
git-tree-sha1 = "5c7cf2f49e6c808ccf6359a6edcf2632c6d4bbe2"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "9a46ad06307e51230a3602527308ee57945d0e36c9662efc69924230ccac1de1"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.12.2+7/Glibc.v2.12.2.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "3d874e2881e9f3715b21fb8dc8ae03c7208b1bcc"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "769560d5dda6e8cae24170f66ab7bfc07677d16a213d9d60d6729478b2cad2ca"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.12.2+7/Glibc.v2.12.2.x86_64-linux-gnu.tar.gz"
