[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "889a67ceb1156bb75feb0e3adf61b577e043da73"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "c243945c5f5abfa3154520a4deb4bd62cde3815b5514883140f3369c5093b393"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.34.0+1/Glibc.v2.34.0.aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c9662cd02afbd4d72f9b06712213466746505ac"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "9b70153f09d178f507afb3739796b43134eba4ded9543fd64d580c5bb53219f0"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.34.0+1/Glibc.v2.34.0.armv6l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c9662cd02afbd4d72f9b06712213466746505ac"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "9b70153f09d178f507afb3739796b43134eba4ded9543fd64d580c5bb53219f0"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.34.0+1/Glibc.v2.34.0.armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "00108e13e5abed919d50b3482fe05e735629004e"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "293fd4d3abfbe3959f9278289cc52dd7dc9288f1074e45931a76712d5ce6d940"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.34.0+1/Glibc.v2.34.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "9d00e3b0c76bcbffcc1f663c16fbb414d63945fa"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "d36f3b8e54b06ee8e6f10cc3f8cefffd1f3132d6e415c7e662e3492bd2b06b86"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.34.0+1/Glibc.v2.34.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "ab07cec406bc84cb03a98eecdf147af9f09b5a3c"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "1a7fac5f9b52f89962d9576a7a25a2b1fa34854981fc020bdd707b255896a875"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.34.0+1/Glibc.v2.34.0.x86_64-linux-gnu.tar.gz"
