[[Glibc]]
arch = "i686"
git-tree-sha1 = "a522ef75bc9ee577158a4cb8235021ab5025087b"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "200f67c5fd4f52418a4d512f3ecf4a010ec5965f24cbb721175ada5f46fdc832"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.25.0+0/Glibc.v2.25.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "3f8197e6bc54f50ef425500bf1c8c77f64f787e9"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "9bcf00bbc4bd9bf16592cab0ae0976fb3c57344f06da0d0333d287ea170649d8"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.25.0+0/Glibc.v2.25.0.x86_64-linux-gnu.tar.gz"
