[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "41d41ccf5ff56c46a0108a5506d31d04ed87a65b"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "11c671f391d27c72ecdaa2a33571d20ebbff092fcccaf5872998e31735c2e6d2"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.25.0+0/Glibc.v2.25.0.x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "8281d40561322eda824f06d70aca0d16fe7555da"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "052738bbea175d4c85b5169871abf6b87a47dd339e29ab43c135caf77bd057da"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.25.0+0/Glibc.v2.25.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "412947b0349d57f8ef049ce4446c82dfdd793133"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "54a950e6345e69663229216b5ae16ae0e4a907872bf7e389a25f7d9aa0d21402"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.25.0+0/Glibc.v2.25.0.aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv7l"
git-tree-sha1 = "28d9627982e4f7ffbe511a5eab34115eeeeeabed"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "dae210781ab6892745bad02c87e405518be3fc333c0255aa1dceb0250f0b5781"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.25.0+0/Glibc.v2.25.0.arm-linux-gnueabihf.tar.gz"
