[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "de28ce44772e8d6b71ae09c4ef93aafd25f2adda"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "e2a6b8e6c52d30e4d2a66dadf6d58e61d5ad92f9a20a0c0ec25d249032decbe6"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+0/Glibc.v2.19.0.aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3573dacfbb8407a0cd77cfe205852df606f479f9"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "249abcd590feb962238199c10ba3a90d5286228742da6bf514c840a8e782cea1"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+0/Glibc.v2.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be6db8fa6de0508680aa23f82ec98ce08617912b"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "c36bcea5c0b33ceb3882bf91ba1488b861ed3d4b60088c8240999ac91c938bdc"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+0/Glibc.v2.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "db12933c4b685c2202cce1e776b9bfff418d8340"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "6b98ace6b1d8997dbf1ab353c083f605ce91f367a2f49719c0814ec8b02dbf02"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+0/Glibc.v2.19.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "e9cb5fe80b1ec4f61a5c001b99b0e594c88c72f3"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "7904fe5bb9f28460594ca4a91a15e6240c4b52ce101d34955c093e20ce32ec95"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+0/Glibc.v2.19.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "b932fd72425d2e28c2d23751d84bf732e76ed272"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "a113adeb8decf0fe956e4146b12091e6f3acc66c66dec7b0afb28597e7c9a8cc"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+0/Glibc.v2.19.0.x86_64-linux-gnu.tar.gz"
