[[Glibc]]
arch = "i686"
git-tree-sha1 = "c4c343101e68a90b1270179d428c3e024744b6a0"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "27fab89da38a9b90ecd2ebee073c0577c18e81eebeb41d65a77e7e64e5524e43"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.12.2+6/Glibc.v2.12.2.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "c2c86f3082818dd188a7a62b1dd3a34cd6b600ca"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "d0ff71f1aece594453a7cfd0c582e09ab350da7650bfc96faae07ec263b5aca1"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.12.2+6/Glibc.v2.12.2.x86_64-linux-gnu.tar.gz"
