[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "221c699e8ea172e93e1e87b65dfb671f2af190c8"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "eb6d6cd6b806aa27982f2ae288ff0a3ebe25e79874e4a218305e863be346d11e"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv7l"
git-tree-sha1 = "e69e77915fa6b99f040828152b98cfb47e3bf136"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "3ff846d1cd58f497e2b9fddc400de656328ed778cdf01e4145809950843a3eac"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "44c5d489c410fa8198657a5d6622141290acc086"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "571c01761f155fd4e18fae9e91d2622f5557a149adb55da035c7d858761a9c8a"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "ffd41faa554ae9e4e8b757df0ae503a68620c216"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "e21730464dee597130882bc57dfe180437eb829134fd8d6ff77d33c64c7e48d0"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "8b619ab5e2dc7fe9ee7e0996ccc3577c71a40c42"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "6f656058edce66971f631ab4c1b402a2b4ef0b0486346946f8d27913a6bdcc0a"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.x86_64-linux-gnu.tar.gz"
