[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "da94d77719806cd240b64fb05ff1694882d04c6f"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "4fd24e28d0e65b351cd422ff422671958b10be82f5565a1f4c87ce40112bc34f"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv7l"
git-tree-sha1 = "69055b4fb804fe933dc574ba4ae096dcfd067044"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "1029cb4313842f9023c1477df479afdf96854d6bac6e810ec18a44d5298272f1"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "469b71c1839ca203d1dbf2c85b9a5c15b5c79b86"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "357c30b520e434da1466fb649d883e8cc1a4a0e2e20f95d1530d7ebece36ccb2"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "3dbf013323e94b450600e95dc4db3c1c1775bb94"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "6b3b4b2e1626a6535d91d54d9f6f44eed0449909588f78fcdee66864c81cd0f3"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "7b30204d03672ef627e6f5a7d4980ecf19ebb127"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ff57e7905aadaf4b0e3b40dff3c00a83d69c5365a801733cc3ef9f2859cfdb25"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.29.0+0/Glibc.v2.29.0.x86_64-linux-gnu.tar.gz"
