[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "c24f6c8f9f3cfa1527222ab552a103258085d1bd"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "97c753a8430efc1782b0f74d9e4da76d90eba61c3814c5d4a2f4a27a73ffa182"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+3/Glibc.v2.19.0.aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "719b0c034167cc0c345c6c7259be1845d010a93d"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "4646e8ff86e6a97409d0590cb881d368611c47f43b158d52ff9c3d7868814c58"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+3/Glibc.v2.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4fedc4cda91b307474a3e5ba4742e779bcc3d990"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "c503f4e5f120aa4431ebd5f33e9b98bc38c570e6bb7f6b647aa1e63fa809eb8d"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.19.0+3/Glibc.v2.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "c3ebd4e81caa88eafce4db666cd455de65f0c430"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "b4156d2cf8f7f0477dcc98fb7d339b557e94becc5ed2f5948578e63446364af1"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.17.0+3/Glibc.v2.17.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "9f9c36e14b695c801f6e6e4041ba3265242444e4"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ed0283415f8d47f667ca0991dabf9bf34f44d0e24dcf0c32fdd98afe3957a880"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.17.0+3/Glibc.v2.17.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "6399b6cade0ba3459dc55fa74e78a07e99c97259"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "e1d98dced278d02e2e65de9e87daf390e3959ed6b87d41cdc646ad4b30c22300"
    url = "https://github.com/JuliaBinaryWrappers/Glibc_jll.jl/releases/download/Glibc-v2.17.0+3/Glibc.v2.17.0.x86_64-linux-gnu.tar.gz"
