# Autogenerated wrapper script for Glibc_jll for armv7l-linux-gnueabihf
JLLWrappers.@generate_wrapper_header("Glibc")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
