# Autogenerated wrapper script for Glibc_jll for powerpc64le-linux-gnu
JLLWrappers.@generate_wrapper_header("Glibc")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
